language: go

go:
    - master
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x

addons:
    chrome: stable

script:
    #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
    - go test -v ./...
