language: go

go:
    - master
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    # - 1.4.x disabled due to url decode bug in chrome 63

addons:
    chrome: stable

before_script:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &

script:
    - sleep 20
    - go test -v
