/*

Package cri provides type-safe bindings for the devtools protocol,
and can be used with Chrome or any other target that implements the interface.

Protocol is generated by script cmd/generate.sh, which fetches the latest version of protocol
and creates types and commands (accessibility, animation, page, dom...) packages.
Script can be run by calling
	go generate

To start using package, create a new connection to chrome
	// connects to 127.0.0.1:9222
	conn, connErr := cri.NewConnection()
Connection instance can now be used to send commands to chrome
	// get Page instance
	pi := page.New(conn)
	// send Page.enable command
	pi.Enable()
	// send Page.navigate command with url parameter
	pi.Navigate(&page.NavigateRequest{Url: "https://www.example.com"})
	// wait till Page.loadEventFired received
	pi.LoadEventFired()

To get started with devtools read https://developers.google.com/web/updates/2017/04/headless-chrome

*/
package cri

//go:generate bash cmd/generate.sh
//go:generate gofmt -s -w .
